artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/sakshipakhrot/End-to-End-Housing-Price-Prediction-Model/main/Data_Set.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/HouseTS_new.parquet
  metro_path: artifacts/data_ingestion/usmetros.csv


data_preprocessing:
  root_dir: artifacts/data_preprocessing
  train_path: artifacts/data_transformation/train.parquet
  eval_path: artifacts/data_transformation/eval.parquet


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_preprocessing/train_processed.parquet
  eval_data_path: artifacts/data_preprocessing/eval_processed.parquet
  

prediction_pipeline:
  root_dir: artifacts/prediction
  model_path: artifacts/model_trainer/model.pkl
  city_coords_lookup_path: artifacts/data_transformation/city_coords_lookup.csv
  zip_counts_path: artifacts/data_preprocessing/zip_counts.pkl